export const MAGIC_STRINGS = {
  userInfo:"userInfo",
  username:"username",
  series:"series",
  password:"password",
  isJuridical:"isJuridical",
  firstname:"firstname",
  surname:"surname",
  patronymic:"patronymic",
  emailCanonical:"emailCanonical",
  passport:"passport",
  email:"email",
  inn:"inn",
  snils:"snils",
  whatsAppAuthModal:"whatsAppAuthModal",
  redirect_url:"redirect_url",
  address:"address",
  addressInProfile:"addressInProfile",
  description:"description",
  number:"number",
  birthday:"birthday",
  issuedAt:"issuedAt",
  phone:"phone",
  usernameCanonical:"usernameCanonical",
  workHours:"workHours",
  verificationPhoneModal: "verificationPhoneModal",
  success: "success",
  error: "error",
  text: "text",
};
export const LOCALES = {
  address: "Адрес",
  addressDefault: "Регион, город, улица",
  login: "Логин",
  password: "Пароль",
  generate: "сгенерировать",
  surname: "Фамилия",
  surnameDefault: "Иванов",
  name: "Имя",
  nameDefault: "Иван",
  patronymic: "Отчество",
  patronymicDefault: "Иванович",
  physical: "Физическое лицо",
  juridical: "Юридическое лицо",
  inn: "ИНН",
  passportSerial: "Серия паспорта",
  passportSerialDefault: "9999",
  passportNumber: "Номер паспорта",
  passportNumberDefault: "123456",
  birthday: "Дата рождения",
  snils: "СНИЛС",
  email: "Электронная почта",
  phone: "Телефон",
  remark: "Примечание",
  workHours: "Рабочие часы",
  phoneConfirmed: "Ваш номер подтверждён",
  phoneNotConfirmed: "Ваш номер не подтверждён",
  whatsappBotEnable: "Подключить бота Whatsapp",
  whatsappNotifyDisable: "Отключить уведомления Whatsapp",
  whatsappNotifyEnable: "Подключить уведомления Whatsapp",
  juridicalError: "Если вы хотите работать как юридическое лицо, то необходимо заключить с нами договор. Для этого вам нужно обратиться в тех. поддержку по телефону +7 (800) 550-50-43, либо написать на почту docs@rosstrah.ru, в теме письма указав свой логин",
};
export const DATES_FORMAT = {
  DDMMYYYY:"DD.MM.YYYY",
}
export const PASSWORD_CHARSET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-=!@#№$;%^:&?*()_+";
export const REGEXP = {
  inn: /^[\d]{0,12}$/,
  passportSerial: /^[\d]{0,4}$/,
  passportNumber: /^[\d]{0,6}$/,
  birthday: /^[.\d]{0,10}$/,
  snils: /^[\d]{0,11}$/,
};
